//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LondonTowerLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LondonTowerLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Blue {
            get {
                object obj = ResourceManager.GetObject("bead_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Blue_Cut {
            get {
                object obj = ResourceManager.GetObject("bead_Blue_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Blue_Cut_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Blue_Cut_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Blue_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Blue_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Green {
            get {
                object obj = ResourceManager.GetObject("bead_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Green_Cut {
            get {
                object obj = ResourceManager.GetObject("bead_Green_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Green_Cut_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Green_Cut_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Green_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Green_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Orange {
            get {
                object obj = ResourceManager.GetObject("bead_Orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Orange_Cut {
            get {
                object obj = ResourceManager.GetObject("bead_Orange_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Orange_Cut_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Orange_Cut_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Orange_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Orange_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Pink {
            get {
                object obj = ResourceManager.GetObject("bead_Pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Pink_Cut {
            get {
                object obj = ResourceManager.GetObject("bead_Pink_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Pink_Cut_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Pink_Cut_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Pink_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Pink_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Yellow {
            get {
                object obj = ResourceManager.GetObject("bead_Yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Yellow_Cut {
            get {
                object obj = ResourceManager.GetObject("bead_Yellow_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Yellow_Cut_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Yellow_Cut_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bead_Yellow_vh {
            get {
                object obj = ResourceManager.GetObject("bead_Yellow_vh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Border {
            get {
                object obj = ResourceManager.GetObject("Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exitButton {
            get {
                object obj = ResourceManager.GetObject("exitButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exitButtonko {
            get {
                object obj = ResourceManager.GetObject("exitButtonko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exitButtonok {
            get {
                object obj = ResourceManager.GetObject("exitButtonok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainboard {
            get {
                object obj = ResourceManager.GetObject("mainboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainboard_ex {
            get {
                object obj = ResourceManager.GetObject("mainboard_ex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peg1 {
            get {
                object obj = ResourceManager.GetObject("peg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peg2 {
            get {
                object obj = ResourceManager.GetObject("peg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peg3 {
            get {
                object obj = ResourceManager.GetObject("peg3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peg4 {
            get {
                object obj = ResourceManager.GetObject("peg4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peg5 {
            get {
                object obj = ResourceManager.GetObject("peg5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pointeur {
            get {
                object obj = ResourceManager.GetObject("Pointeur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Template {
            get {
                object obj = ResourceManager.GetObject("Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;Level&quot;: 3,
        ///  &quot;TestDate&quot;: &quot;0001-01-01T00:00:00&quot;,
        ///  &quot;TrialList&quot;: [
        ///    {
        ///      &quot;PegListGoal&quot;: [
        ///        {
        ///          &quot;PegNumber&quot;: 1,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 1
        ///            }
        ///          ]
        ///        },
        ///        {
        ///          &quot;PegNumber&quot;: 2,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 3
        ///            }
        ///          ]
        ///        },
        ///        {
        ///          &quot;PegNumber&quot;: 3,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 2
        ///    [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TowerOfLondon_Lvl3 {
            get {
                return ResourceManager.GetString("TowerOfLondon_Lvl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;Level&quot;: 4,
        ///  &quot;TestDate&quot;: &quot;0001-01-01T00:00:00&quot;,
        ///  &quot;TrialList&quot;: [
        ///    {
        ///      &quot;PegListGoal&quot;: [
        ///        {
        ///          &quot;PegNumber&quot;: 1,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 3
        ///            }
        ///          ]
        ///        },
        ///        {
        ///          &quot;PegNumber&quot;: 2,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 2
        ///            }
        ///          ]
        ///        },
        ///        {
        ///          &quot;PegNumber&quot;: 3,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 1
        ///    [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TowerOfLondon_Lvl4 {
            get {
                return ResourceManager.GetString("TowerOfLondon_Lvl4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;Level&quot;: 5,
        ///  &quot;TestDate&quot;: &quot;0001-01-01T00:00:00&quot;,
        ///  &quot;TrialList&quot;: [
        ///    {
        ///      &quot;PegListGoal&quot;: [
        ///        {
        ///          &quot;PegNumber&quot;: 1,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 1
        ///            }
        ///          ]
        ///        },
        ///        {
        ///          &quot;PegNumber&quot;: 2,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 3
        ///            }
        ///          ]
        ///        },
        ///        {
        ///          &quot;PegNumber&quot;: 3,
        ///          &quot;BeadList&quot;: [
        ///            {
        ///              &quot;ColorBead&quot;: 0
        ///    [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string TowerOfLondon_Lvl5 {
            get {
                return ResourceManager.GetString("TowerOfLondon_Lvl5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WallpaperTower {
            get {
                object obj = ResourceManager.GetObject("WallpaperTower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wood {
            get {
                object obj = ResourceManager.GetObject("wood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodarrow {
            get {
                object obj = ResourceManager.GetObject("woodarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodarrowko {
            get {
                object obj = ResourceManager.GetObject("woodarrowko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodarrowok {
            get {
                object obj = ResourceManager.GetObject("woodarrowok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton3 {
            get {
                object obj = ResourceManager.GetObject("woodbutton3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton3ko {
            get {
                object obj = ResourceManager.GetObject("woodbutton3ko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton3ok {
            get {
                object obj = ResourceManager.GetObject("woodbutton3ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton4 {
            get {
                object obj = ResourceManager.GetObject("woodbutton4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton4ko {
            get {
                object obj = ResourceManager.GetObject("woodbutton4ko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton4ok {
            get {
                object obj = ResourceManager.GetObject("woodbutton4ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton5 {
            get {
                object obj = ResourceManager.GetObject("woodbutton5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton5ko {
            get {
                object obj = ResourceManager.GetObject("woodbutton5ko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodbutton5ok {
            get {
                object obj = ResourceManager.GetObject("woodbutton5ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio01 {
            get {
                object obj = ResourceManager.GetObject("woodRadio01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio01s {
            get {
                object obj = ResourceManager.GetObject("woodRadio01s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio02 {
            get {
                object obj = ResourceManager.GetObject("woodRadio02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio02s {
            get {
                object obj = ResourceManager.GetObject("woodRadio02s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio03 {
            get {
                object obj = ResourceManager.GetObject("woodRadio03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio03s {
            get {
                object obj = ResourceManager.GetObject("woodRadio03s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio04 {
            get {
                object obj = ResourceManager.GetObject("woodRadio04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio04s {
            get {
                object obj = ResourceManager.GetObject("woodRadio04s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio05 {
            get {
                object obj = ResourceManager.GetObject("woodRadio05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio05s {
            get {
                object obj = ResourceManager.GetObject("woodRadio05s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio06 {
            get {
                object obj = ResourceManager.GetObject("woodRadio06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio06s {
            get {
                object obj = ResourceManager.GetObject("woodRadio06s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio07 {
            get {
                object obj = ResourceManager.GetObject("woodRadio07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio07s {
            get {
                object obj = ResourceManager.GetObject("woodRadio07s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio08 {
            get {
                object obj = ResourceManager.GetObject("woodRadio08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio08s {
            get {
                object obj = ResourceManager.GetObject("woodRadio08s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio09 {
            get {
                object obj = ResourceManager.GetObject("woodRadio09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio09s {
            get {
                object obj = ResourceManager.GetObject("woodRadio09s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio10 {
            get {
                object obj = ResourceManager.GetObject("woodRadio10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap woodRadio10s {
            get {
                object obj = ResourceManager.GetObject("woodRadio10s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
